language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm@latest
before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
env:
  global:
    - DEBUG="sails-orientdb:*,-sails-orientdb:*:debug"
  matrix:
    - ORIENTDB_VERSION=1.7.10
    - ORIENTDB_VERSION=2.0.2
    - ORIENTDB_VERSION=2.1-SNAPSHOT
addons:
  code_climate:
    repo_token: 9048159e3344dd9ba3afbc6044c1648f472de839baf7cc9eb73089b71439052b
